In [181]:
import numpy as np
def tirar_n_dados(n):
    tirada = []
    for n in range(n):
        tirada.append(np.random.randint(1,7))
    return np.array(tirada)

In [183]:
tirar_n_dados(5)

array([2, 1, 6, 3, 4])

In [166]:
def es_generala(x):
    dado=np.unique(x)
    if(len(dado)==1):
        return True
    else:
        return False
    

In [167]:
j=0
for i in range(10000):
    n=tirar_n_dados()
    y=es_generala(n)
    if(y==True):
        j=j+1
        print(n)
print(j)   

[3 3 3 3 3]
[4 4 4 4 4]
[3 3 3 3 3]
[4 4 4 4 4]
[2 2 2 2 2]
5


In [168]:
def seleccionar_mayoria(x):
    unico=np.unique(x)
    freq=np.zeros(len(unico))
    for i in range(len(unico)):
        for j in range(len(x)):
            if unico[i]==x[j]:
                freq[i]+=1
    maximo=unico[np.argmax(freq)]
    frecuencia=int(freq[np.argmax(freq)])
    return maximo,frecuencia     
    

In [169]:
n=tirar_n_dados()
print(seleccionar_mayoria(n))

(3, 2)


In [191]:
def jugar(n_tiradas= 3, dados_total= 5):
    n_dados = dados_total 
    dados_mesa = np.array([]) 
    tiradas = np.zeros((n_tiradas,dados_total))
    tirada_exitosa= 0
    contador_tiradas=0   
    
    while (contador_tiradas < n_tiradas) and tirada_exitosa == 0:
        dados_nuevos = tirar_n_dados(n_dados)
        todos_dados = np.concatenate ((dados_nuevos,dados_mesa))
        tiradas[contador_tiradas]= todos_dados
        
        if es_generala(todos_dados):
            tirada_exitosa = contador_tiradas+1
        else:
            maximo, frecuencia = seleccionar_mayoria (todos_dados)
            dados_mesa = np.repeat(maximo, frecuencia)
            n_dados = dados_total -len(dados_mesa) 
        contador_tiradas+=1
        
    return tiradas, tirada_exitosa

In [192]:
for i in range(20000):
    tiradas, tirada_exitosa = jugar(3,5)
    if tirada_exitosa >=0:
        print(tiradas, tirada_exitosa)

[[3. 4. 2. 6. 2.]
 [4. 3. 5. 2. 2.]
 [5. 4. 3. 2. 2.]] 0
[[3. 1. 5. 1. 1.]
 [2. 3. 1. 1. 1.]
 [6. 2. 1. 1. 1.]] 0
[[4. 4. 1. 6. 5.]
 [5. 1. 6. 4. 4.]
 [5. 4. 3. 4. 4.]] 0
[[1. 1. 2. 1. 1.]
 [6. 1. 1. 1. 1.]
 [6. 1. 1. 1. 1.]] 0
[[5. 6. 4. 2. 6.]
 [6. 2. 3. 6. 6.]
 [5. 4. 6. 6. 6.]] 0
[[4. 5. 6. 1. 1.]
 [3. 6. 4. 1. 1.]
 [1. 1. 3. 1. 1.]] 0
[[6. 2. 3. 6. 6.]
 [6. 2. 6. 6. 6.]
 [3. 6. 6. 6. 6.]] 0
[[5. 1. 3. 2. 4.]
 [6. 6. 1. 4. 1.]
 [5. 1. 2. 1. 1.]] 0
[[4. 1. 6. 6. 1.]
 [5. 3. 5. 1. 1.]
 [2. 6. 3. 1. 1.]] 0
[[4. 2. 2. 3. 5.]
 [3. 2. 1. 2. 2.]
 [4. 3. 2. 2. 2.]] 0
[[6. 5. 2. 4. 6.]
 [1. 2. 6. 6. 6.]
 [6. 1. 6. 6. 6.]] 0
[[1. 3. 1. 1. 5.]
 [1. 4. 1. 1. 1.]
 [5. 1. 1. 1. 1.]] 0
[[4. 5. 5. 6. 6.]
 [4. 2. 1. 5. 5.]
 [5. 6. 6. 5. 5.]] 0
[[6. 5. 2. 3. 6.]
 [6. 3. 2. 6. 6.]
 [3. 4. 6. 6. 6.]] 0
[[5. 2. 6. 4. 2.]
 [5. 3. 6. 2. 2.]
 [2. 3. 2. 2. 2.]] 0
[[6. 2. 5. 4. 4.]
 [4. 6. 3. 4. 4.]
 [5. 5. 4. 4. 4.]] 0
[[5. 5. 4. 1. 4.]
 [6. 2. 4. 4. 4.]
 [5. 5. 4. 4. 4.]] 0
[[1. 3. 4. 5. 3.]
 [4. 2. 1. 3.